services:
  webserv:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8081:8081"